package io.argus.cli.export;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class HtmlExporterTest {

    @Test
    void basicHtml_containsStructure() {
        String html = HtmlExporter.toHtml("Hello World", "Test");
        assertTrue(html.contains("<!DOCTYPE html>"));
        assertTrue(html.contains("<title>Test</title>"));
        assertTrue(html.contains("Hello World"));
        assertTrue(html.contains("Generated by Argus"));
    }

    @Test
    void ansiColors_convertedToSpans() {
        String input = "\033[32mGreen\033[0m Normal \033[31mRed\033[0m";
        String result = HtmlExporter.convertAnsiToHtml(input);

        assertTrue(result.contains("<span class=\"green\">Green</span>"));
        assertTrue(result.contains("<span class=\"red\">Red</span>"));
        assertTrue(result.contains("Normal"));
    }

    @Test
    void boldAndDim_converted() {
        String input = "\033[1mBold\033[0m \033[2mDim\033[0m";
        String result = HtmlExporter.convertAnsiToHtml(input);

        assertTrue(result.contains("class=\"bold\""));
        assertTrue(result.contains("class=\"dim\""));
    }

    @Test
    void combinedCodes_multipleClasses() {
        String input = "\033[1;36mBoldCyan\033[0m";
        String result = HtmlExporter.convertAnsiToHtml(input);

        assertTrue(result.contains("bold"));
        assertTrue(result.contains("cyan"));
    }

    @Test
    void htmlEntities_escaped() {
        String input = "a < b > c & d";
        String result = HtmlExporter.convertAnsiToHtml(input);

        assertTrue(result.contains("&lt;"));
        assertTrue(result.contains("&gt;"));
        assertTrue(result.contains("&amp;"));
        assertFalse(result.contains(" < "));
    }

    @Test
    void noAnsi_passthrough() {
        String input = "Plain text with no escapes";
        String result = HtmlExporter.convertAnsiToHtml(input);
        assertEquals("Plain text with no escapes", result);
    }

    @Test
    void title_htmlEscaped() {
        String html = HtmlExporter.toHtml("content", "Title <script>alert('xss')</script>");
        assertTrue(html.contains("&lt;script&gt;"));
        assertFalse(html.contains("<script>"));
    }
}
