package io.argus.cli.export;

/**
 * Converts ANSI-colored terminal output to self-contained HTML.
 * Used by --export=html flag on doctor, report, gclog commands.
 */
public final class HtmlExporter {

    private HtmlExporter() {}

    /**
     * Convert ANSI terminal output to a self-contained HTML document.
     * Preserves colors by mapping ANSI escape codes to CSS spans.
     */
    public static String toHtml(String ansiOutput, String title) {
        StringBuilder html = new StringBuilder();
        html.append("<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n");
        html.append("<meta charset=\"UTF-8\">\n");
        html.append("<title>").append(escapeHtml(title)).append("</title>\n");
        html.append("<style>\n");
        html.append("body { background: #1e1e2e; color: #cdd6f4; font-family: 'JetBrains Mono', 'Fira Code', monospace; font-size: 14px; padding: 24px; }\n");
        html.append("pre { white-space: pre-wrap; word-wrap: break-word; line-height: 1.5; }\n");
        html.append(".bold { font-weight: bold; }\n");
        html.append(".dim { opacity: 0.6; }\n");
        html.append(".red { color: #f38ba8; }\n");
        html.append(".green { color: #a6e3a1; }\n");
        html.append(".yellow { color: #f9e2af; }\n");
        html.append(".blue { color: #89b4fa; }\n");
        html.append(".magenta { color: #cba6f7; }\n");
        html.append(".cyan { color: #94e2d5; }\n");
        html.append(".white { color: #cdd6f4; }\n");
        html.append(".header { color: #94e2d5; font-size: 16px; margin-bottom: 8px; }\n");
        html.append(".footer { color: #6c7086; font-size: 12px; margin-top: 16px; }\n");
        html.append("</style>\n</head>\n<body>\n<pre>\n");

        // Parse ANSI escape codes and convert to HTML spans
        html.append(convertAnsiToHtml(ansiOutput));

        html.append("\n</pre>\n");
        html.append("<div class=\"footer\">Generated by Argus JVM Diagnostic Toolkit</div>\n");
        html.append("</body>\n</html>");
        return html.toString();
    }

    static String convertAnsiToHtml(String input) {
        StringBuilder out = new StringBuilder();
        int i = 0;
        boolean inSpan = false;

        while (i < input.length()) {
            if (i < input.length() - 1 && input.charAt(i) == '\033' && input.charAt(i + 1) == '[') {
                // Parse ANSI escape sequence
                int end = input.indexOf('m', i + 2);
                if (end < 0) { i++; continue; }

                String codes = input.substring(i + 2, end);
                i = end + 1;

                if (inSpan) {
                    out.append("</span>");
                    inSpan = false;
                }

                if (codes.equals("0") || codes.isEmpty()) {
                    // Reset — just close span
                    continue;
                }

                String cssClass = ansiToClass(codes);
                if (!cssClass.isEmpty()) {
                    out.append("<span class=\"").append(cssClass).append("\">");
                    inSpan = true;
                }
            } else {
                char c = input.charAt(i);
                switch (c) {
                    case '<' -> out.append("&lt;");
                    case '>' -> out.append("&gt;");
                    case '&' -> out.append("&amp;");
                    default -> out.append(c);
                }
                i++;
            }
        }

        if (inSpan) out.append("</span>");
        return out.toString();
    }

    private static String ansiToClass(String codes) {
        StringBuilder classes = new StringBuilder();
        for (String code : codes.split(";")) {
            switch (code.trim()) {
                case "1" -> append(classes, "bold");
                case "2" -> append(classes, "dim");
                case "31" -> append(classes, "red");
                case "32" -> append(classes, "green");
                case "33" -> append(classes, "yellow");
                case "34" -> append(classes, "blue");
                case "35" -> append(classes, "magenta");
                case "36" -> append(classes, "cyan");
                case "37" -> append(classes, "white");
                default -> {} // ignore unknown codes
            }
        }
        return classes.toString();
    }

    private static void append(StringBuilder sb, String cls) {
        if (!sb.isEmpty()) sb.append(' ');
        sb.append(cls);
    }

    private static String escapeHtml(String s) {
        return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;");
    }
}
