Args = --no-fallback \
       --enable-url-protocols=http \
       -H:+ReportExceptionStackTraces \
       --initialize-at-build-time=io.argus.cli \
       --initialize-at-build-time=io.argus.core \
       --initialize-at-run-time=io.argus.cli.instrument
